{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "8b41a1ab_da8186d7",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 797
      },
      "writtenOn": "2023-05-07T21:07:03Z",
      "side": 1,
      "message": "Looks like some python 3.10 issue again ðŸ˜ž",
      "revId": "de6c0ad932757faa90c1c11d9c6a0b8ea096579e",
      "serverId": "7fc14799-209e-464c-9743-7a06c2c21a81"
    }
  ]
}